apiVersion: template.openshift.io/v1https
kind: Template
labels:
message: "Service template for msr"
metadata:
  annotations:
    description: "Service template for msr"
  name: msr-service-template
  namespace: ${DEPLOY_NAMESPACE}  
objects:

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${IMAGE_NAME}
      labels:
        name: ${IMAGE_NAME}
    spec:
      type: ClusterIP
      ports:
      - port: 80
        targetPort: 5555
        name: http
      - port: 443
        targetPort: 5543
        name: https
      selector:
        app: ${IMAGE_NAME}

parameters:
  - name: DEPLOY_NAMESPACE
    required: true
  - name: IMAGE_NAME
    required: true    