apiVersion: template.openshift.io/v1
kind: Template
labels:
message: "Route template for msr"
metadata:
  annotations:
    description: "Route template for msr"
  name: msr-route-template
  namespace: ${DEPLOY_NAMESPACE}  
objects:

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${IMAGE_NAME}
      namespace: ${DEPLOY_NAMESPACE}  
      labels:
        name: ${IMAGE_NAME}
    spec:
      host: app-${IMAGE_NAME}${ROUTE_SUBDOMAIN}
      to:
        kind: Service
        name: ${IMAGE_NAME}
        weight: 100
      port:
        targetPort: 5555

parameters:
  - name: DEPLOY_NAMESPACE
    required: true
  - name: ROUTE_SUBDOMAIN
    required: true
  - name: IMAGE_NAME
    required: true    
