apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus
  name: sm-dce-msr-personnes
spec:
  endpoints:
    - interval: 10s
      port: http
      scheme: http
  selector:
    matchLabels:
      app: dce-msr-personnes