parameters:
  FROM_PLATFORM: "mycontainers-v1"
  FROM_IMAGE: "msr-dce-dev:10.15.fix7.1"
  FROM_NAMESPACE: "ea7-integrationdsit-grp-hp"
  DEPLOY_NAMESPACE: "ea7-integrationdsit-grp-hp"
  IMAGE_NAME: "dce-msr-personnes"
  BUILD_NAMESPACE: "ea7-integrationdsit-grp-hp"
  MAINTAINER_EMAIL: "stephane-externe.tailland@edf.fr"
  AWS_ACCOUNT: "cloud-aws-hp-131539360861"
  ECR_URI: "131539360861.dkr.ecr.eu-west-1.amazonaws.com"
  ROUTE_SUBDOMAIN: ".grp-hp.caas-int-hp.automation.edf.fr"

