apiVersion: v1
kind: ConfigMap
metadata:
  name: dce-msr-personnes
data:
  application.properties: |
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionEnabled=true
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.databaseName=pocsag
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.datasourceClass=org.postgresql.ds.PGSimpleDataSource
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.portNumber=5432
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.serverName=pg-pocsag.clzdcpofefi7.eu-west-1.rds.amazonaws.com
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.user=postgres
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.password=$secret{DB_PASSWORD}
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.maximumPoolSize=10
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc.connectionSettings.transactionType=LOCAL_TRANSACTION
    artConnection.dcePersonnes.dcePersonnes.jdbc.dcePersonnes_jdbc_oracle.connectionEnabled=false

    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp://umserver-h:9000
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jms.DEFAULT_IS_JMS_CONNECTION.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.csqSize=0
    jms.DEFAULT_IS_JMS_CONNECTION.jndi_jndiAliasName=DEFAULT_IS_JNDI_PROVIDER
    jms.DEFAULT_IS_JMS_CONNECTION.jndi_automaticallyCreateUMAdminObjects=true
    jms.DEFAULT_IS_JMS_CONNECTION.producerMaxRetryAttempts=30
    jms.DEFAULT_IS_JMS_CONNECTION.producerRetryInterval=1000

    sftpserver.sftp.hostName=ip-172-16-2-64.eu-west-1.compute.internal
    sftpserver.sftp.port=22
    sftpserver.sftp.hostKey=YzNOb0xXVmtNalUxTVRrZ1FVRkJRVU16VG5waFF6RnNXa1JKTVU1VVJUVkJRVUZCU1VVeFVqTlRjVEEwUnl0UE5sUkhOV2h4VG1FdlJYbDZaM1poUkZsbGVVcFpZelIyTkZSS2NHeFpWa0U9
    sftpserver.sftp.preferredKeyExchangeAlgorithm=curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,rsa2048-sha256,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,rsa1024-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1,curve25519-sha256
    sftpserver.sftp.preferredMACS2C=hmac-sha2-512-96,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-etm@openssh.com,hmac-md5-96,hmac-sha2-512-etm@openssh.com
    sftpserver.sftp.preferredMACC2S=hmac-sha2-512-96,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-etm@openssh.com,hmac-md5-96,hmac-sha2-512-etm@openssh.com
    sftpserver.sftp.preferredCiphersS2C=aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,arcfour256,aes256-cbc,3des-cbc,3des-ctr,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,aes256-gcm@openssh.com
    sftpserver.sftp.preferredCiphersC2S=aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,arcfour256,aes256-cbc,3des-cbc,3des-ctr,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,aes256-gcm@openssh.com
    sftpuser.sftp_user.sftpServerAlias=sftp
    sftpuser.sftp_user.userName=pocsag
    sftpuser.sftp_user.password=$secret{SFTP_USER_PASSWORD}
    globalvariable.SFTP_FOLDER.value=/poc/proftpd/sftp/pocsag

    cloudstreamsconnection.dcePersonnes.dcePersonnes..aws\:dcePersonnes_aws_s3.connectionconfiguration.aws..accessKey=$secret{S3_ACCESS_KEY}
    cloudstreamsconnection.dcePersonnes.dcePersonnes..aws\:dcePersonnes_aws_s3.connectionconfiguration.aws..secretKey=$secret{S3_SECRET_KEY}
    cloudstreamsconnection.dcePersonnes.dcePersonnes..aws\:dcePersonnes_aws_s3.connectionconfiguration.aws..region=eu-west-1
    cloudstreamsconnection.dcePersonnes.dcePersonnes..aws\:dcePersonnes_aws_s3.connectionconfiguration.cn..providerUrl=https://s3.eu-west-1.amazonaws.com
    globalvariable.S3_BUCKET.value=dp-bucket-s3-poc
    globalvariable.S3_PERSONNES_FOLDER.value=POCSAG

    globalvariable.SERVER.value=$env{SERVER}
    globalvariable.TEMP_DIR.value=/tmp/work

    globalvariable.WEBHDFS_URL.value=http://ec2-34-247-69-117.eu-west-1.compute.amazonaws.com:9870/webhdfs/v1
    globalvariable.HDFS_PERSONNES_FOLDER.value=/user/hadoop/pocsag
    globalvariable.HDFS_USER.value=hadoop

    jdbc.wmdb.dbURL=jdbc:wm:postgresql://pg-pocsag.clzdcpofefi7.eu-west-1.rds.amazonaws.com:5432;databaseName=wm;EncryptionMethod=SSL;ValidateServerCertificate=false
    jdbc.wmdb.userid=postgres
    jdbc.wmdb.password=$secret{WM_DB_PASSWORD}
    jdbc.wmdb.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
    jdbcfunc.ISCoreAudit.connPoolAlias=wmdb
    jdbcfunc.ISInternal.connPoolAlias=wmdb
    jdbcfunc.ProcessAudit.connPoolAlias=wmdb

    settings.watt.net.default.accept=application/json
    settings.watt.server.ns.lockingMode=none
    settings.watt.net.localhost=https://dce-msr-personnes:443

    user.Administrator.password=$secret{ADMIN_PASSWORD}

  applicationFile.properties:  |

  node.idf: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Values version="2.0">
      <value name="node_type">HDFSConnectionData</value>
      <value name="node_subtype">unknown</value>
      <value name="node_nsName">dcePersonnes.aws:dcePersonnes_aws_emr</value>
      <value name="node_pkg">dcePersonnes</value>
      <value name="is_public">false</value>
      <record name="HDFSConnectionData" javaclass="com.wm.util.Values">
        <value name="description">EMR</value>
        <value name="namenodeUri">hdfs://ip-172-16-2-83.eu-west-1.compute.internal:8020</value>
        <number name="replication" type="Short">1</number>
        <number name="blockSize" type="Long">1</number>
        <number name="bufferSize" type="Integer">4</number>
        <value name="connectionstate">enabled</value>
        <value name="authType">NO_AUTH</value>
        <value name="user">hdfs</value>
        <value name="group">hdfsadmingroup</value>
        <value name="coreSiteFilePath"></value>
        <value name="hdfsSiteFilePath"></value>
      </record>
    </Values>