apiVersion: v1
kind: Service
metadata:
  name: msr-personnes
  labels:
    name: msr-personnes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5555
    name: http
  - port: 443
    targetPort: 5543
    name: https
  selector:
    app: msr-personnes
